// Reading, Listening and Mock-Exam modules — the back half of the study loop
// (Learn -> Drill -> Read -> Listen -> Test). Content lives in lazy-loaded banks
// (js/data/reading.js, js/data/listening.js). The mock exam assembles its
// Language-Knowledge section from FULL_VOCAB_DB and its Reading/Listening
// sections from those banks. Reuses globals from app.js: speakJapanese, player,
// updateHUDDisplays, saveGameData, generateProceduralQuestions.
(function () {
    const LEVELS = ['N5', 'N4', 'N3', 'N2', 'N1'];
    const loadedSrc = {};

    // UI chrome strings. English defaults live here; native translations come from
    // window.UI_I18N[code] (js/lang/ui.js) when a native language is selected.
    const STRINGS = {
        'p.readingTitle': 'Reading Practice',
        'p.readingIntro': 'Original JLPT-style passages with comprehension questions. Practice material, not official exam content.',
        'p.listeningTitle': 'Listening Practice',
        'p.listeningIntro': "Audio is generated by your browser's Japanese voice — great for training comprehension, not a substitute for native recordings. Play, answer, then check the transcript.",
        'p.examTitle': 'Mock Exam',
        'p.examIntro': 'A short, timed JLPT-style test in three sections — Language Knowledge, Reading, Listening. You pass only if you clear <strong>100/180 overall AND at least 19/60 in every section</strong>, exactly like the real exam. Practice material, not official content.',
        'p.showEn': 'Show English translation',
        'p.showTranslation': 'Show translation',
        'p.backReading': 'Reading list',
        'p.backListening': 'Listening list',
        'p.backExam': 'Back to mock exams',
        'p.playAudio': 'Play audio',
        'p.slow': 'Slow', 'p.normal': 'Normal', 'p.fast': 'Fast',
        'p.startExam': 'Start {lv} mock exam',
        'p.submit': 'Submit exam',
        'p.secLK': 'Language Knowledge', 'p.secReading': 'Reading', 'p.secListening': 'Listening',
        'p.pass': 'PASS', 'p.notYet': 'NOT YET', 'p.below19': 'below 19',
        'p.passNote': 'Pass needs 100/180 overall and 19/60 in every section.',
        'p.result': 'You got {c} / {t} correct.',
        'p.comingReading': 'More {lv} passages coming soon.',
        'p.comingListening': 'More {lv} clips coming soon.'
    };
    function t(key, vars) {
        const code = (typeof LANG_PACK_CODES !== 'undefined' && typeof player !== 'undefined') ? LANG_PACK_CODES[player.nativeLanguage] : null;
        let s = (code && window.UI_I18N && window.UI_I18N[code] && window.UI_I18N[code][key]) || STRINGS[key] || key;
        if (vars) for (const k in vars) s = s.split('{' + k + '}').join(vars[k]);
        return s;
    }

    function loadScript(src, cb) {
        if (loadedSrc[src]) { cb(); return; }
        const s = document.createElement('script');
        s.src = src;
        s.onload = () => { loadedSrc[src] = true; cb(); };
        s.onerror = () => { console.log('practice: failed to load', src); cb(); };
        document.head.appendChild(s);
    }

    // Award XP/gold on the same level-up curve as the arena.
    // ponytail: mirrors the arena's inline level-up (checkBattleResolution); a
    // 6-line dup beats refactoring that hot path just to share it.
    function award(xp, gold) {
        if (typeof player === 'undefined') return;
        player.xp += xp; player.gold += gold;
        while (player.xp >= player.maxXp) {
            player.level++; player.xp -= player.maxXp;
            player.maxHp += 20; player.hp = player.maxHp;
            player.maxXp = Math.round(player.maxXp * 1.5);
        }
        if (typeof updateHUDDisplays === 'function') updateHUDDisplays();
        if (typeof saveGameData === 'function') saveGameData();
    }

    // random n items (for exam variety across attempts)
    function pickN(arr, n) {
        return [...arr].sort(() => Math.random() - 0.5).slice(0, n);
    }

    function levelPills(current, onPick) {
        const wrap = document.createElement('div');
        wrap.className = 'practice-levels';
        LEVELS.forEach(lv => {
            const b = document.createElement('button');
            b.type = 'button';
            b.className = 'practice-level' + (lv === current ? ' active' : '');
            b.textContent = lv;
            b.onclick = () => onPick(lv);
            wrap.appendChild(b);
        });
        return wrap;
    }

    // Render MC questions into `container`. `answer` is the index of the correct
    // option. Calls onDone(correctCount) once every question is answered.
    function renderQuestions(container, questions, onDone, parentItem) {
        let answered = 0, correct = 0;
        questions.forEach((qq, qi) => {
            const card = document.createElement('div');
            card.className = 'practice-q';
            const qt = document.createElement('div');
            qt.className = 'practice-q-text';
            qt.textContent = (qi + 1) + '. ' + qq.q;
            card.appendChild(qt);
            const code = (typeof LANG_PACK_CODES !== 'undefined' && typeof player !== 'undefined') ? LANG_PACK_CODES[player.nativeLanguage] : null;
            const nativeQ = (code && qq['q_' + code]) || qq.q_en;
            if (nativeQ) {
                const en = document.createElement('div');
                en.className = 'practice-q-en';
                en.textContent = nativeQ;
                card.appendChild(en);
            }
            const opts = document.createElement('div');
            opts.className = 'practice-opts';
            let locked = false;

            const explBox = document.createElement('div');
            explBox.className = 'practice-explanation';
            explBox.style.display = 'none';

            qq.options.forEach((opt, oi) => {
                const ob = document.createElement('button');
                ob.type = 'button';
                ob.className = 'practice-opt';
                ob.textContent = opt;
                ob.onclick = () => {
                    if (locked) return;
                    locked = true;
                    answered++;
                    const isRight = (oi === qq.answer);
                    if (isRight) correct++;
                    else ob.classList.add('wrong');
                    opts.children[qq.answer].classList.add('right');

                    // Show Explanation Card
                    explBox.style.display = 'block';
                    explBox.style.marginTop = '12px';
                    explBox.style.padding = '12px 14px';
                    explBox.style.borderRadius = '8px';
                    explBox.style.fontSize = '0.85rem';
                    explBox.style.lineHeight = '1.45';
                    explBox.style.border = isRight ? '1px solid rgba(32,191,107,0.3)' : '1px solid rgba(255,118,117,0.3)';
                    explBox.style.background = isRight ? 'rgba(32,191,107,0.08)' : 'rgba(255,118,117,0.08)';

                    const correctOptText = qq.options[qq.answer];
                    const explText = (code && qq['explanation_' + code]) || qq.explanation_en || qq.explanation ||
                        `Correct answer: "${correctOptText}". This option directly matches the authentic details in the passage.`;

                    explBox.innerHTML = `
                        <div style="font-weight: 700; color: ${isRight ? 'var(--accent-teal, #20bf6b)' : 'var(--accent-pink, #ff7675)'}; margin-bottom: 4px; display: flex; align-items: center; gap: 6px;">
                            <i class="fa-solid ${isRight ? 'fa-circle-check' : 'fa-circle-xmark'}"></i>
                            <span>${isRight ? (t('p.correct') || 'Correct! (正解)') : (t('p.incorrect') || 'Incorrect')}</span>
                        </div>
                        <div style="color: #ddd;">${explText}</div>
                    `;

                    if (answered === questions.length && onDone) onDone(correct);
                };
                opts.appendChild(ob);
            });
            card.appendChild(opts);
            card.appendChild(explBox);
            container.appendChild(card);
        });
    }

    function backButton(label, onClick) {
        const b = document.createElement('button');
        b.type = 'button';
        b.className = 'practice-back';
        b.innerHTML = '<i class="fa-solid fa-arrow-left"></i> ' + label;
        b.onclick = onClick;
        return b;
    }

    function detailsBlock(summary, text) {
        const d = document.createElement('details');
        d.className = 'practice-details';
        const s = document.createElement('summary');
        s.textContent = summary;
        d.appendChild(s);
        const p = document.createElement('div');
        p.className = 'practice-details-body';
        p.textContent = text;
        d.appendChild(p);
        return d;
    }

    // ---- READING ----
    function renderReading(defaultLevel) {
        const root = document.getElementById('reading');
        if (!root) return;
        loadScript('js/data/reading.js', () => {
            const bank = window.READING_BANK || {};
            const validLevels = ['N5', 'N4', 'N3', 'N2', 'N1'];
            let level = (defaultLevel && validLevels.includes(defaultLevel.toUpperCase())) ? defaultLevel.toUpperCase() : 'N5';
            root.innerHTML = '';
            const head = document.createElement('div');
            head.className = 'glass-card';
            head.innerHTML = '<div class="card-title"><i class="fa-solid fa-book-reader" style="color: var(--accent-teal);"></i> ' + t('p.readingTitle') + '</div>'
                + '<p class="practice-intro">' + t('p.readingIntro') + '</p>';
            const body = document.createElement('div');
            head.appendChild(body);
            root.appendChild(head);

            const showList = (lv) => {
                level = lv;
                body.innerHTML = '';
                body.appendChild(levelPills(level, showList));
                const items = bank[lv] || [];
                if (!items.length) {
                    const p = document.createElement('p');
                    p.className = 'practice-empty';
                    p.textContent = t('p.comingReading', { lv });
                    body.appendChild(p);
                    return;
                }
                items.forEach(it => {
                    const c = document.createElement('button');
                    c.type = 'button';
                    c.className = 'practice-item';
                    const t = document.createElement('span');
                    t.className = 'practice-item-title';
                    t.textContent = it.title;
                    c.appendChild(t);
                    c.onclick = () => openReading(it, lv, showList);
                    body.appendChild(c);
                });
            };
            showList(level);
        });
    }

    function openReading(item, lv, backToList) {
        if (typeof window.markDailyMission === 'function') window.markDailyMission('read');
        const root = document.getElementById('reading');
        root.innerHTML = '';
        const card = document.createElement('div');
        card.className = 'glass-card';
        card.appendChild(backButton(t('p.backReading'), () => renderReading()));
        const title = document.createElement('div');
        title.className = 'card-title';
        title.textContent = item.title;
        card.appendChild(title);

        // Listen to Passage Audio Controls
        const audioBar = document.createElement('div');
        audioBar.className = 'reading-audio-bar';
        audioBar.style.cssText = 'display: flex; align-items: center; gap: 8px; margin: 10px 0 14px 0; padding: 8px 12px; border-radius: 8px; background: rgba(0,0,0,0.2); border: 1px solid rgba(255,255,255,0.08);';
        
        let rate = 0.9;
        const playBtn = document.createElement('button');
        playBtn.type = 'button';
        playBtn.className = 'btn listening-play';
        playBtn.style.cssText = 'padding: 6px 14px; font-size: 0.85rem; font-weight: 600; border-radius: 20px;';
        playBtn.innerHTML = '<i class="fa-solid fa-volume-high"></i> Listen to Passage (朗読)';
        playBtn.onclick = () => {
            if (typeof speakJapanese === 'function') speakJapanese(item.passage, rate);
        };
        audioBar.appendChild(playBtn);

        [[t('p.slow') || 'Slow', 0.6], [t('p.normal') || 'Normal', 0.9], [t('p.fast') || 'Fast', 1.1]].forEach(([lab, r]) => {
            const b = document.createElement('button');
            b.type = 'button';
            b.className = 'listening-speed' + (r === rate ? ' active' : '');
            b.textContent = lab;
            b.onclick = () => {
                rate = r;
                audioBar.querySelectorAll('.listening-speed').forEach(x => x.classList.remove('active'));
                b.classList.add('active');
            };
            audioBar.appendChild(b);
        });
        card.appendChild(audioBar);

        const passage = document.createElement('div');
        passage.className = 'reading-passage';
        passage.textContent = item.passage;
        card.appendChild(passage);
        const code = (typeof LANG_PACK_CODES !== 'undefined' && typeof player !== 'undefined') ? LANG_PACK_CODES[player.nativeLanguage] : null;
        const nativePassage = (code && item['passage_' + code]) || item.passage_en;
        const toggleLabel = (code && code !== 'en') ? (t('p.showTranslation') || 'Show translation') : t('p.showEn');
        if (nativePassage) card.appendChild(detailsBlock(toggleLabel, nativePassage));

        // Key Vocabulary / Educational Helpers
        if (item.vocab && item.vocab.length) {
            const vBlock = document.createElement('details');
            vBlock.className = 'practice-details';
            vBlock.style.marginTop = '10px';
            const vSummary = document.createElement('summary');
            vSummary.innerHTML = '<i class="fa-solid fa-book-bookmark" style="color:var(--accent-gold);"></i> Key Vocabulary & Readings (語彙)';
            vBlock.appendChild(vSummary);
            const vBody = document.createElement('div');
            vBody.className = 'practice-details-body';
            vBody.innerHTML = item.vocab.map(v => `
                <div style="display: flex; justify-content: space-between; padding: 4px 0; border-bottom: 1px solid rgba(255,255,255,0.05);">
                    <span style="font-weight: 700; color: #fff;">${v.ja} (${v.reading})</span>
                    <span style="color: #bbb;">${v[code] || v.en}</span>
                </div>
            `).join('');
            vBlock.appendChild(vBody);
            card.appendChild(vBlock);
        }

        const qWrap = document.createElement('div');
        qWrap.className = 'practice-questions';
        card.appendChild(qWrap);
        const result = document.createElement('div');
        card.appendChild(result);
        renderQuestions(qWrap, item.questions, (correct) => {
            const total = item.questions.length;
            award(10 + correct * 3, correct * 2);
            result.className = 'practice-result';
            result.textContent = t('p.result', { c: correct, t: total }) + '  +' + (10 + correct * 3) + ' XP';
        }, item);
        root.appendChild(card);
    }

    // ---- LISTENING ----
    function renderListening(defaultLevel) {
        const root = document.getElementById('listening');
        if (!root) return;
        loadScript('js/data/listening.js', () => {
            const bank = window.LISTENING_BANK || {};
            const validLevels = ['N5', 'N4', 'N3', 'N2', 'N1'];
            let level = (defaultLevel && validLevels.includes(defaultLevel.toUpperCase())) ? defaultLevel.toUpperCase() : 'N5';
            root.innerHTML = '';
            const head = document.createElement('div');
            head.className = 'glass-card';
            head.innerHTML = '<div class="card-title"><i class="fa-solid fa-headphones" style="color: var(--accent-pink);"></i> ' + t('p.listeningTitle') + '</div>'
                + '<p class="practice-intro">' + t('p.listeningIntro') + '</p>';
            const body = document.createElement('div');
            head.appendChild(body);
            root.appendChild(head);

            const showList = (lv) => {
                level = lv;
                body.innerHTML = '';
                body.appendChild(levelPills(level, showList));
                const items = bank[lv] || [];
                if (!items.length) {
                    const p = document.createElement('p');
                    p.className = 'practice-empty';
                    p.textContent = t('p.comingListening', { lv });
                    body.appendChild(p);
                    return;
                }
                items.forEach(it => {
                    const c = document.createElement('button');
                    c.type = 'button';
                    c.className = 'practice-item';
                    const t = document.createElement('span');
                    t.className = 'practice-item-title';
                    t.textContent = it.title;
                    c.appendChild(t);
                    c.onclick = () => openListening(it);
                    body.appendChild(c);
                });
            };
            showList(level);
        });
    }

    function openListening(item) {
        if (typeof window.markDailyMission === 'function') window.markDailyMission('read');
        const root = document.getElementById('listening');
        root.innerHTML = '';
        const card = document.createElement('div');
        card.className = 'glass-card';
        card.appendChild(backButton(t('p.backListening'), () => renderListening()));
        const title = document.createElement('div');
        title.className = 'card-title';
        title.textContent = item.title;
        card.appendChild(title);

        // Play controls: play + speed. Script is hidden until answered.
        const controls = document.createElement('div');
        controls.className = 'listening-controls';
        let rate = 0.9;
        const play = document.createElement('button');
        play.type = 'button';
        play.className = 'btn listening-play';
        play.innerHTML = '<i class="fa-solid fa-play"></i> ' + t('p.playAudio');
        play.onclick = () => { if (typeof speakJapanese === 'function') speakJapanese(item.script, rate); };
        controls.appendChild(play);
        [[t('p.slow'), 0.6], [t('p.normal'), 0.9], [t('p.fast'), 1.1]].forEach(([lab, r], i) => {
            const b = document.createElement('button');
            b.type = 'button';
            b.className = 'listening-speed' + (r === rate ? ' active' : '');
            b.textContent = lab;
            b.onclick = () => {
                rate = r;
                controls.querySelectorAll('.listening-speed').forEach(x => x.classList.remove('active'));
                b.classList.add('active');
            };
            controls.appendChild(b);
        });
        card.appendChild(controls);

        const qWrap = document.createElement('div');
        qWrap.className = 'practice-questions';
        card.appendChild(qWrap);
        const after = document.createElement('div');
        card.appendChild(after);
        renderQuestions(qWrap, item.questions, (correct) => {
            const total = item.questions.length;
            award(10 + correct * 3, correct * 2);
            after.innerHTML = '';
            const res = document.createElement('div');
            res.className = 'practice-result';
            res.textContent = t('p.result', { c: correct, t: total }) + '  +' + (10 + correct * 3) + ' XP';
            after.appendChild(res);
            const script = document.createElement('div');
            script.className = 'listening-script';
            script.textContent = item.script;
            after.appendChild(script);
            const code = (typeof LANG_PACK_CODES !== 'undefined' && typeof player !== 'undefined') ? LANG_PACK_CODES[player.nativeLanguage] : null;
            const nativeTranscript = (code && item['transcript_' + code]) || item.transcript_en;
            const toggleLabel = (code && code !== 'en') ? (t('p.showTranslation') || 'Show translation') : t('p.showEn');
            if (nativeTranscript) after.appendChild(detailsBlock(toggleLabel, nativeTranscript));
        }, item);
        root.appendChild(card);
    }

    // ---- MOCK EXAM ----
    // Three timed sections with sectional pass thresholds, mirroring the real
    // JLPT gating (overall >= 100/180 AND each section >= 19/60).
    function renderExam(defaultLevel) {
        const root = document.getElementById('exam');
        if (!root) return;
        // exam pulls from both banks
        loadScript('js/data/reading.js', () => loadScript('js/data/listening.js', () => {
            const validLevels = ['N5', 'N4', 'N3', 'N2', 'N1'];
            let level = (defaultLevel && validLevels.includes(defaultLevel.toUpperCase())) ? defaultLevel.toUpperCase() : 'N5';
            root.innerHTML = '';
            const head = document.createElement('div');
            head.className = 'glass-card';
            head.innerHTML = '<div class="card-title"><i class="fa-solid fa-file-pen" style="color: var(--accent-purple);"></i> ' + t('p.examTitle') + '</div>'
                + '<p class="practice-intro">' + t('p.examIntro') + '</p>';
            const body = document.createElement('div');
            head.appendChild(body);
            root.appendChild(head);

            const rebuild = (lv) => {
                level = lv;
                body.innerHTML = '';
                body.appendChild(levelPills(level, rebuild));
                const start = document.createElement('button');
                start.type = 'button';
                start.className = 'btn exam-start';
                start.innerHTML = '<i class="fa-solid fa-stopwatch"></i> ' + t('p.startExam', { lv });
                start.onclick = () => runExam(lv);
                body.appendChild(start);
            };
            rebuild(level);
        }));
    }

    function buildVocabSection(lv, count) {
        // reuse the arena's procedural vocab/reading questions; normalise answer to index
        if (typeof generateProceduralQuestions !== 'function') return [];
        const raw = generateProceduralQuestions(lv, count) || [];
        return raw.filter(q => q && q.options && q.options.length).map(q => ({
            q: q.q,
            options: q.options,
            answer: Math.max(0, q.options.indexOf(q.answer))
        }));
    }

    function runExam(lv) {
        const readingBank = (window.READING_BANK || {})[lv] || [];
        const listeningBank = (window.LISTENING_BANK || {})[lv] || [];
        const sections = [
            { key: 'Language Knowledge', type: 'vocab', questions: buildVocabSection(lv, 10) },
            { key: 'Reading', type: 'reading', items: pickN(readingBank, 2) },
            { key: 'Listening', type: 'listening', items: pickN(listeningBank, 2) }
        ];

        const root = document.getElementById('exam');
        root.innerHTML = '';
        const card = document.createElement('div');
        card.className = 'glass-card';
        root.appendChild(card);

        // Timer bar
        const bar = document.createElement('div');
        bar.className = 'exam-bar';
        const timeEl = document.createElement('span');
        timeEl.className = 'exam-timer';
        bar.appendChild(timeEl);
        const submitBtn = document.createElement('button');
        submitBtn.type = 'button';
        submitBtn.className = 'btn exam-submit';
        submitBtn.textContent = t('p.submit');
        bar.appendChild(submitBtn);
        card.appendChild(bar);

        const secLabel = (k) => t(k === 'Language Knowledge' ? 'p.secLK' : k === 'Reading' ? 'p.secReading' : 'p.secListening');
        // track score per section: {section: {correct, total}}
        const score = {};
        sections.forEach(s => { score[s.key] = { correct: 0, total: 0 }; });

        // record answers: for each rendered question, store correctness getter
        const graders = [];

        sections.forEach(sec => {
            const secEl = document.createElement('div');
            secEl.className = 'exam-section';
            const h = document.createElement('div');
            h.className = 'exam-section-title';
            h.textContent = secLabel(sec.key);
            secEl.appendChild(h);

            if (sec.type === 'vocab') {
                sec.questions.forEach(q => graders.push(mkGrader(secEl, sec.key, q)));
            } else {
                (sec.items || []).forEach(item => {
                    if (sec.type === 'reading') {
                        const p = document.createElement('div');
                        p.className = 'reading-passage';
                        p.textContent = item.passage;
                        secEl.appendChild(p);
                    } else {
                        const play = document.createElement('button');
                        play.type = 'button';
                        play.className = 'btn listening-play';
                        play.innerHTML = '<i class="fa-solid fa-play"></i> ' + t('p.playAudio');
                        play.onclick = () => { if (typeof speakJapanese === 'function') speakJapanese(item.script, 0.9); };
                        secEl.appendChild(play);
                    }
                    (item.questions || []).forEach(q => graders.push(mkGrader(secEl, sec.key, q)));
                });
            }
            card.appendChild(secEl);
        });

        // Grader: renders a question, returns {section, isCorrect()}.
        function mkGrader(parent, sectionKey, q) {
            score[sectionKey].total++;
            const box = document.createElement('div');
            box.className = 'practice-q';
            const qt = document.createElement('div');
            qt.className = 'practice-q-text';
            qt.textContent = q.q;
            box.appendChild(qt);
            const opts = document.createElement('div');
            opts.className = 'practice-opts';
            let chosen = -1;
            q.options.forEach((opt, oi) => {
                const ob = document.createElement('button');
                ob.type = 'button';
                ob.className = 'practice-opt';
                ob.textContent = opt;
                ob.onclick = () => {
                    chosen = oi;
                    opts.querySelectorAll('.practice-opt').forEach(x => x.classList.remove('chosen'));
                    ob.classList.add('chosen');
                };
                opts.appendChild(ob);
            });
            box.appendChild(opts);
            parent.appendChild(box);
            return { sectionKey, opts, q, isCorrect: () => chosen === q.answer, reveal: () => {
                opts.children[q.answer] && opts.children[q.answer].classList.add('right');
            } };
        }

        // Timer: ~1 min per question, min 5 min.
        let remaining = Math.max(300, graders.length * 45);
        const fmt = (s) => String(Math.floor(s / 60)).padStart(2, '0') + ':' + String(s % 60).padStart(2, '0');
        timeEl.textContent = '⏱ ' + fmt(remaining);
        let done = false;
        const tick = setInterval(() => {
            remaining--;
            timeEl.textContent = '⏱ ' + fmt(remaining);
            if (remaining <= 0) finish();
        }, 1000);

        function finish() {
            if (done) return;
            done = true;
            clearInterval(tick);
            graders.forEach(g => {
                if (g.isCorrect()) score[g.sectionKey].correct++;
                g.reveal();
            });
            // scale each section to /60
            let overall = 0; const lines = []; let sectionalFail = false;
            sections.forEach(s => {
                const sc = score[s.key];
                const scaled = sc.total ? Math.round((sc.correct / sc.total) * 60) : 0;
                overall += scaled;
                if (scaled < 19) sectionalFail = true;
                lines.push(`${secLabel(s.key)}: ${scaled}/60${scaled < 19 ? '  ✕ ' + t('p.below19') : ''}`);
            });
            const passed = overall >= 100 && !sectionalFail;
            award(passed ? 80 : Math.round(overall / 3), passed ? 40 : 10);

            const res = document.createElement('div');
            res.className = 'exam-result ' + (passed ? 'pass' : 'fail');
            res.innerHTML = `<div class="exam-verdict">${passed ? t('p.pass') : t('p.notYet')} — ${overall}/180</div>`
                + lines.map(l => `<div class="exam-line">${l}</div>`).join('')
                + `<div class="exam-note">${t('p.passNote')}</div>`;

            // Social Brag / Viral Share Tray
            const shareText = `🏯 I scored ${overall}/180 (${passed ? 'PASS 🎉' : 'NOT YET 💪'}) on the JLPT ${lv} Mock Exam on KotoQuest!\n`
                + lines.map(l => `• ${l}`).join('\n') + '\n\n'
                + `Free, offline JLPT study academy: https://kotoquest.pages.dev/#exam?level=${lv}`;

            const shareTray = document.createElement('div');
            shareTray.className = 'share-tray';
            shareTray.innerHTML = `
                <span class="share-label"><i class="fa-solid fa-share-nodes"></i> Share:</span>
                ${passed ? '<button type="button" class="share-btn share-btn-primary" id="btn-claim-cert"><i class="fa-solid fa-award"></i> Claim Certificate</button>' : ''}
                <button type="button" class="share-btn share-btn-primary" id="btn-share-native"><i class="fa-solid fa-share-from-square"></i> Share Score</button>
                <a class="share-btn share-btn-wa" href="https://api.whatsapp.com/send?text=${encodeURIComponent(shareText)}" target="_blank" rel="noopener"><i class="fa-brands fa-whatsapp"></i> WhatsApp</a>
                <a class="share-btn share-btn-x" href="https://twitter.com/intent/tweet?text=${encodeURIComponent(shareText)}" target="_blank" rel="noopener"><i class="fa-brands fa-x-twitter"></i> Post</a>
                <button type="button" class="share-btn share-btn-copy" id="btn-share-copy"><i class="fa-solid fa-copy"></i> Copy</button>
            `;
            res.appendChild(shareTray);

            const btnCert = shareTray.querySelector('#btn-claim-cert');
            if (btnCert) {
                btnCert.onclick = () => {
                    if (typeof window.openCertificateModal === 'function') {
                        window.openCertificateModal();
                    } else {
                        window.location.hash = '#certificate';
                    }
                };
            }

            const btnNative = shareTray.querySelector('#btn-share-native');
            if (btnNative) {
                btnNative.onclick = () => {
                    if (navigator.share) {
                        navigator.share({
                            title: `KotoQuest - JLPT ${lv} Mock Exam`,
                            text: shareText,
                            url: `https://kotoquest.pages.dev/#exam?level=${lv}`
                        }).catch(() => {});
                    } else {
                        navigator.clipboard.writeText(shareText);
                        if (typeof window.showToast === 'function') window.showToast('Score copied to clipboard!');
                    }
                };
            }
            const btnCopy = shareTray.querySelector('#btn-share-copy');
            if (btnCopy) {
                btnCopy.onclick = () => {
                    navigator.clipboard.writeText(shareText);
                    if (typeof window.showToast === 'function') window.showToast('Score copied to clipboard!');
                };
            }

            card.insertBefore(res, card.children[1]);
            const retry = document.createElement('button');
            retry.type = 'button';
            retry.className = 'btn';
            retry.style.marginTop = '14px';
            retry.textContent = t('p.backExam');
            retry.onclick = () => renderExam(lv);
            card.appendChild(retry);
            res.scrollIntoView({ block: 'start', behavior: 'smooth' });
        }
        submitBtn.onclick = finish;
    }

    // Lazy-render each module the first time its tab is opened (and on resume).
    const RENDERERS = { reading: renderReading, listening: renderListening, exam: renderExam };
    const rendered = {};
    function ensureRendered(tab, level) {
        if (!RENDERERS[tab]) return;
        rendered[tab] = true;
        RENDERERS[tab](level);
    }
    // Allow external callers to render a practice tab directly with an optional level
    window.renderPracticeTab = function(tab, level) {
        if (RENDERERS[tab]) {
            ensureRendered(tab, level);
        }
    };
    // Allow external callers (e.g. applyNativeLanguageNuances in app.js) to re-render
    // practice modules in the newly selected language.
    window.refreshPracticeModules = function() {
        for (const tab in rendered) {
            if (rendered[tab] && RENDERERS[tab]) {
                RENDERERS[tab]();
            }
        }
    };

    document.addEventListener('DOMContentLoaded', () => {
        const nav = document.getElementById('main-nav');
        if (nav) nav.addEventListener('click', (e) => {
            const t = e.target.closest('.nav-tab');
            if (t) ensureRendered(t.getAttribute('data-tab'));
        });
        // resume: if the app restored one of our tabs, render it
        if (typeof player !== 'undefined' && player.lastTab && RENDERERS[player.lastTab]) {
            ensureRendered(player.lastTab);
        }
    });
})();
