// Reading, Listening and Mock-Exam modules — the back half of the study loop
// (Learn -> Drill -> Read -> Listen -> Test). Content lives in lazy-loaded banks
// (js/data/reading.js, js/data/listening.js). The mock exam assembles its
// Language-Knowledge section from FULL_VOCAB_DB and its Reading/Listening
// sections from those banks. Reuses globals from app.js: speakJapanese, player,
// updateHUDDisplays, saveGameData, generateProceduralQuestions.
(function () {
    const LEVELS = ['N5', 'N4', 'N3', 'N2', 'N1'];
    const loadedSrc = {};

    // UI chrome strings. English defaults live here; native translations come from
    // window.UI_I18N[code] (js/lang/ui.js) when a native language is selected.
    const STRINGS = {
        'p.readingTitle': 'Reading Practice',
        'p.readingIntro': 'Original JLPT-style passages with comprehension questions. Practice material, not official exam content.',
        'p.tabBooks': 'Storybook Library',
        'p.tabPassages': 'JLPT Passages',
        'p.booksIntro': 'Read authentic Japanese folk tales and literary masterpieces from Aozora Bunko with dual-language audio narration, sentence breakdowns, and vocabulary glossaries.',
        'p.readBook': 'Read Book',
        'p.allLevels': 'All Levels',
        'p.chapter': 'Chapter {n}',
        'p.sentenceMode': 'Sentence by Sentence',
        'p.passageMode': 'Full Story',
        'p.showRomaji': 'Romaji',
        'p.vocabTitle': 'Chapter Vocabulary',
        'p.quizTitle': 'Comprehension Quiz',
        'p.backBooks': 'Back to Library',
        'p.listenChapter': 'Listen to Chapter',
        'p.readingMinutes': '{m} min read',
        'p.listeningTitle': 'Listening Practice',
        'p.listeningIntro': "Audio is generated by your browser's Japanese voice — great for training comprehension, not a substitute for native recordings. Play, answer, then check the transcript.",
        'p.examTitle': 'Mock Exam',
        'p.examIntro': 'A short, timed JLPT-style test in three sections — Language Knowledge, Reading, Listening. You pass only if you clear <strong>100/180 overall AND at least 19/60 in every section</strong>, exactly like the real exam. Practice material, not official content.',
        'p.showEn': 'Show English translation',
        'p.showTranslation': 'Show translation',
        'p.backReading': 'Reading list',
        'p.backListening': 'Listening list',
        'p.backExam': 'Back to mock exams',
        'p.playAudio': 'Play audio',
        'p.slow': 'Slow', 'p.normal': 'Normal', 'p.fast': 'Fast',
        'p.startExam': 'Start {lv} mock exam',
        'p.submit': 'Submit exam',
        'p.secLK': 'Language Knowledge', 'p.secReading': 'Reading', 'p.secListening': 'Listening',
        'p.pass': 'PASS', 'p.notYet': 'NOT YET', 'p.below19': 'below 19',
        'p.passNote': 'Pass needs 100/180 overall and 19/60 in every section.',
        'p.result': 'You got {c} / {t} correct.',
        'p.comingReading': 'More {lv} passages coming soon.',
        'p.comingListening': 'More {lv} clips coming soon.'
    };
    function t(key, vars) {
        const code = (typeof LANG_PACK_CODES !== 'undefined' && typeof player !== 'undefined') ? LANG_PACK_CODES[player.nativeLanguage] : null;
        let s = (code && window.UI_I18N && window.UI_I18N[code] && window.UI_I18N[code][key]) || STRINGS[key] || key;
        if (vars) for (const k in vars) s = s.split('{' + k + '}').join(vars[k]);
        return s;
    }

    function loadScript(src, cb) {
        if (loadedSrc[src]) { cb(); return; }
        const s = document.createElement('script');
        s.src = src;
        s.onload = () => { loadedSrc[src] = true; cb(); };
        s.onerror = () => { console.log('practice: failed to load', src); cb(); };
        document.head.appendChild(s);
    }

    // Award XP/gold on the same level-up curve as the arena.
    // ponytail: mirrors the arena's inline level-up (checkBattleResolution); a
    // 6-line dup beats refactoring that hot path just to share it.
    function award(xp, gold) {
        if (typeof player === 'undefined') return;
        player.xp += xp; player.gold += gold;
        while (player.xp >= player.maxXp) {
            player.level++; player.xp -= player.maxXp;
            player.maxHp += 20; player.hp = player.maxHp;
            player.maxXp = Math.round(player.maxXp * 1.5);
        }
        if (typeof updateHUDDisplays === 'function') updateHUDDisplays();
        if (typeof saveGameData === 'function') saveGameData();
    }

    // random n items (for exam variety across attempts)
    function pickN(arr, n) {
        return [...arr].sort(() => Math.random() - 0.5).slice(0, n);
    }

    function levelPills(current, onPick) {
        const wrap = document.createElement('div');
        wrap.className = 'practice-levels';
        LEVELS.forEach(lv => {
            const b = document.createElement('button');
            b.type = 'button';
            b.className = 'practice-level' + (lv === current ? ' active' : '');
            b.textContent = lv;
            b.onclick = () => onPick(lv);
            wrap.appendChild(b);
        });
        return wrap;
    }

    // Render MC questions into `container`. `answer` is the index of the correct
    // option. Calls onDone(correctCount) once every question is answered.
    function renderQuestions(container, questions, onDone) {
        let answered = 0, correct = 0;
        questions.forEach((qq, qi) => {
            const card = document.createElement('div');
            card.className = 'practice-q';
            const qt = document.createElement('div');
            qt.className = 'practice-q-text';
            qt.textContent = (qi + 1) + '. ' + qq.q;
            card.appendChild(qt);
            const code = (typeof LANG_PACK_CODES !== 'undefined' && typeof player !== 'undefined') ? LANG_PACK_CODES[player.nativeLanguage] : null;
            const nativeQ = (code && qq['q_' + code]) || qq.q_en;
            if (nativeQ) {
                const en = document.createElement('div');
                en.className = 'practice-q-en';
                en.textContent = nativeQ;
                card.appendChild(en);
            }
            const opts = document.createElement('div');
            opts.className = 'practice-opts';
            let locked = false;
            qq.options.forEach((opt, oi) => {
                const ob = document.createElement('button');
                ob.type = 'button';
                ob.className = 'practice-opt';
                ob.textContent = opt;
                ob.onclick = () => {
                    if (locked) return;
                    locked = true;
                    answered++;
                    if (oi === qq.answer) correct++;
                    else ob.classList.add('wrong');
                    opts.children[qq.answer].classList.add('right');
                    if (answered === questions.length && onDone) onDone(correct);
                };
                opts.appendChild(ob);
            });
            card.appendChild(opts);
            container.appendChild(card);
        });
    }

    function backButton(label, onClick) {
        const b = document.createElement('button');
        b.type = 'button';
        b.className = 'practice-back';
        b.innerHTML = '<i class="fa-solid fa-arrow-left"></i> ' + label;
        b.onclick = onClick;
        return b;
    }

    function detailsBlock(summary, text) {
        const d = document.createElement('details');
        d.className = 'practice-details';
        const s = document.createElement('summary');
        s.textContent = summary;
        d.appendChild(s);
        const p = document.createElement('div');
        p.className = 'practice-details-body';
        p.textContent = text;
        d.appendChild(p);
        return d;
    }

    // ---- READING & STORYBOOK LIBRARY ----
    let currentReadingTab = 'books'; // 'books' or 'passages'

    function renderReading(defaultLevel, subTab) {
        const root = document.getElementById('reading');
        if (!root) return;
        if (subTab) currentReadingTab = subTab;
        const validLevels = ['ALL', 'N5', 'N4', 'N3', 'N2', 'N1'];
        let level = (defaultLevel && validLevels.includes(defaultLevel.toUpperCase())) ? defaultLevel.toUpperCase() : 'ALL';

        root.innerHTML = '';
        const head = document.createElement('div');
        head.className = 'glass-card';

        // Sub-navigation bar: Storybook Library vs JLPT Passages
        const subnav = document.createElement('div');
        subnav.className = 'library-subnav';
        
        const btnBooks = document.createElement('button');
        btnBooks.type = 'button';
        btnBooks.className = 'subnav-btn' + (currentReadingTab === 'books' ? ' active' : '');
        btnBooks.innerHTML = '<i class="fa-solid fa-book-open"></i> ' + t('p.tabBooks');
        btnBooks.onclick = () => renderReading(level, 'books');
        subnav.appendChild(btnBooks);

        const btnPassages = document.createElement('button');
        btnPassages.type = 'button';
        btnPassages.className = 'subnav-btn' + (currentReadingTab === 'passages' ? ' active' : '');
        btnPassages.innerHTML = '<i class="fa-solid fa-file-lines"></i> ' + t('p.tabPassages');
        btnPassages.onclick = () => renderReading(level === 'ALL' ? 'N5' : level, 'passages');
        subnav.appendChild(btnPassages);

        head.appendChild(subnav);

        const titleDiv = document.createElement('div');
        titleDiv.className = 'card-title';
        titleDiv.innerHTML = currentReadingTab === 'books'
            ? '<i class="fa-solid fa-book-reader" style="color: var(--accent-teal);"></i> ' + t('p.tabBooks') + ' <span style="font-size: 0.9rem; opacity: 0.7; font-weight: normal;">(日本文学・民話ライブラリ)</span>'
            : '<i class="fa-solid fa-file-lines" style="color: var(--accent-teal);"></i> ' + t('p.readingTitle');
        head.appendChild(titleDiv);

        const introP = document.createElement('p');
        introP.className = 'practice-intro';
        introP.innerHTML = currentReadingTab === 'books' ? t('p.booksIntro') : t('p.readingIntro');
        head.appendChild(introP);

        const body = document.createElement('div');
        head.appendChild(body);
        root.appendChild(head);

        if (currentReadingTab === 'books') {
            loadScript('js/data/books.js', () => {
                const books = window.JAPANESE_BOOKS || [];
                const langCode = (typeof LANG_PACK_CODES !== 'undefined' && typeof player !== 'undefined') ? LANG_PACK_CODES[player.nativeLanguage] : 'en';

                const showBooks = (lv) => {
                    level = lv;
                    body.innerHTML = '';

                    // Level filter pills: All, N5, N4, N3, N2, N1
                    const filterWrap = document.createElement('div');
                    filterWrap.className = 'practice-levels';
                    ['ALL', 'N5', 'N4', 'N3', 'N2', 'N1'].forEach(l => {
                        const b = document.createElement('button');
                        b.type = 'button';
                        b.className = 'practice-level' + (l === level ? ' active' : '');
                        b.textContent = l === 'ALL' ? t('p.allLevels') : l;
                        b.onclick = () => showBooks(l);
                        filterWrap.appendChild(b);
                    });
                    body.appendChild(filterWrap);

                    const filtered = level === 'ALL' ? books : books.filter(b => b.level.includes(level));
                    if (!filtered.length) {
                        const empty = document.createElement('p');
                        empty.className = 'practice-empty';
                        empty.textContent = t('p.comingReading', { lv: level });
                        body.appendChild(empty);
                        return;
                    }

                    const grid = document.createElement('div');
                    grid.className = 'books-grid';
                    filtered.forEach(book => {
                        const card = document.createElement('div');
                        card.className = 'book-card';

                        const top = document.createElement('div');
                        top.className = 'book-card-top';

                        const badge = document.createElement('span');
                        badge.className = 'book-level-badge ' + (book.levelClass || 'n5');
                        badge.textContent = book.level;
                        top.appendChild(badge);

                        const time = document.createElement('span');
                        time.className = 'book-time-badge';
                        time.innerHTML = '<i class="fa-regular fa-clock"></i> ' + t('p.readingMinutes', { m: book.estimatedMinutes });
                        top.appendChild(time);
                        card.appendChild(top);

                        const jaTitle = document.createElement('div');
                        jaTitle.className = 'book-card-title-ja';
                        jaTitle.textContent = book.title;
                        card.appendChild(jaTitle);

                        const natTitle = document.createElement('div');
                        natTitle.className = 'book-card-title-native';
                        natTitle.textContent = (langCode && book['title_' + langCode]) || book.title_en;
                        card.appendChild(natTitle);

                        const author = document.createElement('div');
                        author.className = 'book-card-author';
                        author.textContent = book.author;
                        card.appendChild(author);

                        const syn = document.createElement('div');
                        syn.className = 'book-card-synopsis';
                        syn.textContent = (langCode && book['synopsis_' + langCode]) || book.synopsis_en;
                        card.appendChild(syn);

                        const footer = document.createElement('div');
                        footer.className = 'book-card-footer';

                        const chCount = document.createElement('span');
                        chCount.className = 'book-chapter-count';
                        chCount.textContent = book.chapters.length + ' ' + (t('p.chapter', { n: '' })).trim() + 's';
                        footer.appendChild(chCount);

                        const readBtn = document.createElement('button');
                        readBtn.type = 'button';
                        readBtn.className = 'book-read-btn';
                        readBtn.innerHTML = '<i class="fa-solid fa-book-reader"></i> ' + t('p.readBook');
                        readBtn.onclick = () => openBookReader(book, 0);
                        footer.appendChild(readBtn);

                        card.appendChild(footer);
                        grid.appendChild(card);
                    });
                    body.appendChild(grid);
                };

                showBooks(level);
            });
        } else {
            // JLPT Passages tab
            loadScript('js/data/reading.js', () => {
                const bank = window.READING_BANK || {};
                const showList = (lv) => {
                    level = lv;
                    body.innerHTML = '';
                    body.appendChild(levelPills(level, showList));
                    const items = bank[lv] || [];
                    if (!items.length) {
                        const p = document.createElement('p');
                        p.className = 'practice-empty';
                        p.textContent = t('p.comingReading', { lv });
                        body.appendChild(p);
                        return;
                    }
                    items.forEach(it => {
                        const c = document.createElement('button');
                        c.type = 'button';
                        c.className = 'practice-item';
                        const tit = document.createElement('span');
                        tit.className = 'practice-item-title';
                        tit.textContent = it.title;
                        c.appendChild(tit);
                        c.onclick = () => openReading(it, lv, showList);
                        body.appendChild(c);
                    });
                };
                showList(level === 'ALL' ? 'N5' : level);
            });
        }
    }

    function openBookReader(book, chapterIndex) {
        const root = document.getElementById('reading');
        if (!root) return;
        root.innerHTML = '';

        const langCode = (typeof LANG_PACK_CODES !== 'undefined' && typeof player !== 'undefined') ? LANG_PACK_CODES[player.nativeLanguage] : 'en';
        const chapter = book.chapters[chapterIndex] || book.chapters[0];
        let displayMode = 'sentence'; // 'sentence' or 'full'
        let showRomaji = true;

        const card = document.createElement('div');
        card.className = 'glass-card';

        // Back button
        card.appendChild(backButton(t('p.backBooks'), () => renderReading(book.level, 'books')));

        // Reader top bar with Title, Chapter selector, Mode toggle, Romaji toggle
        const topBar = document.createElement('div');
        topBar.className = 'reader-top-bar';

        const titleBox = document.createElement('div');
        titleBox.innerHTML = '<h2 style="color: #fff; margin: 0 0 4px; font-size: 1.35rem;">' + book.title + '</h2>'
            + '<div style="color: var(--accent-teal); font-weight: 600; font-size: 0.95rem;">' + ((langCode && book['title_' + langCode]) || book.title_en) + '</div>';
        topBar.appendChild(titleBox);

        const controls = document.createElement('div');
        controls.className = 'reader-controls';

        // Chapter selector
        const select = document.createElement('select');
        select.className = 'reader-chapter-select';
        book.chapters.forEach((ch, idx) => {
            const opt = document.createElement('option');
            opt.value = idx;
            const chTitle = (langCode && ch['title_' + langCode]) || ch.title_en || ch.title;
            opt.textContent = t('p.chapter', { n: ch.chapter }) + ': ' + chTitle;
            if (idx === chapterIndex) opt.selected = true;
            select.appendChild(opt);
        });
        select.onchange = (e) => openBookReader(book, parseInt(e.target.value, 10));
        controls.appendChild(select);

        // Mode toggles
        const btnSent = document.createElement('button');
        btnSent.type = 'button';
        btnSent.className = 'reader-ctrl-btn active';
        btnSent.innerHTML = '<i class="fa-solid fa-list-ul"></i> ' + t('p.sentenceMode');

        const btnFull = document.createElement('button');
        btnFull.type = 'button';
        btnFull.className = 'reader-ctrl-btn';
        btnFull.innerHTML = '<i class="fa-solid fa-align-left"></i> ' + t('p.passageMode');

        btnSent.onclick = () => {
            displayMode = 'sentence';
            btnSent.classList.add('active');
            btnFull.classList.remove('active');
            renderChapterBody();
        };
        btnFull.onclick = () => {
            displayMode = 'full';
            btnFull.classList.add('active');
            btnSent.classList.remove('active');
            renderChapterBody();
        };
        controls.appendChild(btnSent);
        controls.appendChild(btnFull);

        // Romaji toggle
        const btnRomaji = document.createElement('button');
        btnRomaji.type = 'button';
        btnRomaji.className = 'reader-ctrl-btn active';
        btnRomaji.innerHTML = '<i class="fa-solid fa-font"></i> ' + t('p.showRomaji');
        btnRomaji.onclick = () => {
            showRomaji = !showRomaji;
            btnRomaji.classList.toggle('active', showRomaji);
            renderChapterBody();
        };
        controls.appendChild(btnRomaji);

        topBar.appendChild(controls);
        card.appendChild(topBar);

        // Chapter content container
        const contentContainer = document.createElement('div');
        card.appendChild(contentContainer);

        function renderChapterBody() {
            contentContainer.innerHTML = '';

            const chHeader = document.createElement('div');
            chHeader.style.margin = '14px 0 18px';
            const localizedChTitle = (langCode && chapter['title_' + langCode]) || chapter.title_en || chapter.title;
            chHeader.innerHTML = '<h3 style="color: #fff; margin: 0 0 4px; font-size: 1.15rem;">' + t('p.chapter', { n: chapter.chapter }) + ' — ' + chapter.title + '</h3>'
                + '<div style="color: var(--text-muted); font-size: 0.9rem;">' + localizedChTitle + '</div>';
            contentContainer.appendChild(chHeader);

            if (displayMode === 'sentence' && Array.isArray(chapter.sentences) && chapter.sentences.length) {
                const sList = document.createElement('div');
                sList.className = 'sentence-list';
                chapter.sentences.forEach(s => {
                    const sc = document.createElement('div');
                    sc.className = 'sentence-card';

                    const sTop = document.createElement('div');
                    sTop.className = 'sentence-card-top';

                    const sJa = document.createElement('div');
                    sJa.className = 'sentence-text-ja';
                    sJa.textContent = s.ja;
                    sTop.appendChild(sJa);

                    const audioBtn = document.createElement('button');
                    audioBtn.type = 'button';
                    audioBtn.className = 'sentence-audio-btn';
                    audioBtn.title = 'Speak';
                    audioBtn.innerHTML = '<i class="fa-solid fa-volume-high"></i>';
                    audioBtn.onclick = () => {
                        if (typeof speakJapanese === 'function') speakJapanese(s.ja);
                    };
                    sTop.appendChild(audioBtn);
                    sc.appendChild(sTop);

                    if (showRomaji && s.romaji) {
                        const sRom = document.createElement('div');
                        sRom.className = 'sentence-romaji-line';
                        sRom.textContent = s.romaji;
                        sc.appendChild(sRom);
                    }

                    const transText = (langCode && s[langCode]) || s.en;
                    if (transText) {
                        const sTrans = document.createElement('div');
                        sTrans.className = 'sentence-trans-box';
                        sTrans.textContent = transText;
                        sc.appendChild(sTrans);
                    }

                    sList.appendChild(sc);
                });
                contentContainer.appendChild(sList);
            } else {
                // Full passage mode
                const fullWrap = document.createElement('div');

                const listenBtn = document.createElement('button');
                listenBtn.type = 'button';
                listenBtn.className = 'reader-ctrl-btn active';
                listenBtn.style.marginBottom = '12px';
                listenBtn.innerHTML = '<i class="fa-solid fa-circle-play"></i> ' + t('p.listenChapter');
                listenBtn.onclick = () => {
                    if (typeof speakJapanese === 'function') speakJapanese(chapter.passage);
                };
                fullWrap.appendChild(listenBtn);

                const passDiv = document.createElement('div');
                passDiv.className = 'reading-passage';
                passDiv.textContent = chapter.passage;
                fullWrap.appendChild(passDiv);

                const natPass = (langCode && chapter['passage_' + langCode]) || chapter.passage_en;
                if (natPass) {
                    const toggleLabel = (langCode && langCode !== 'en') ? t('p.showTranslation') : t('p.showEn');
                    fullWrap.appendChild(detailsBlock(toggleLabel, natPass));
                }
                contentContainer.appendChild(fullWrap);
            }

            // Chapter Vocabulary table
            if (Array.isArray(chapter.vocab) && chapter.vocab.length) {
                const vCard = document.createElement('div');
                vCard.className = 'vocab-table-card';
                vCard.innerHTML = '<div style="font-weight: 700; color: #fff; font-size: 1.05rem; margin-bottom: 8px;"><i class="fa-solid fa-spell-check" style="color: var(--accent-teal);"></i> ' + t('p.vocabTitle') + '</div>';

                const tableWrap = document.createElement('div');
                tableWrap.className = 'vocab-table-wrap';
                const table = document.createElement('table');
                table.className = 'vocab-table';
                table.innerHTML = '<thead><tr>'
                    + '<th class="vocab-th">Kanji</th>'
                    + '<th class="vocab-th">Reading</th>'
                    + '<th class="vocab-th">Romaji</th>'
                    + '<th class="vocab-th">Meaning</th>'
                    + '</tr></thead>';

                const tbody = document.createElement('tbody');
                chapter.vocab.forEach(v => {
                    const tr = document.createElement('tr');
                    const meaning = (langCode && v[langCode]) || v.en;
                    tr.innerHTML = '<td class="vocab-td"><span class="vocab-kanji">' + v.kanji + ' <button type="button" class="sentence-audio-btn" style="width:24px;height:24px;font-size:0.75rem;" data-speak-kanji="' + v.kanji + '"><i class="fa-solid fa-volume-high"></i></button></span></td>'
                        + '<td class="vocab-td"><span class="vocab-kana">' + v.kana + '</span></td>'
                        + '<td class="vocab-td"><span class="vocab-romaji">' + v.romaji + '</span></td>'
                        + '<td class="vocab-td">' + meaning + '</td>';
                    tbody.appendChild(tr);
                });
                table.appendChild(tbody);
                tableWrap.appendChild(table);
                vCard.appendChild(tableWrap);

                // Add click listeners to kanji audio buttons
                vCard.querySelectorAll('[data-speak-kanji]').forEach(btn => {
                    btn.onclick = () => {
                        const w = btn.getAttribute('data-speak-kanji');
                        if (typeof speakJapanese === 'function') speakJapanese(w);
                    };
                });

                contentContainer.appendChild(vCard);
            }

            // Chapter Comprehension Quiz
            if (Array.isArray(chapter.questions) && chapter.questions.length) {
                const qCard = document.createElement('div');
                qCard.style.marginTop = '28px';
                qCard.innerHTML = '<div style="font-weight: 700; color: #fff; font-size: 1.05rem; margin-bottom: 8px;"><i class="fa-solid fa-circle-question" style="color: var(--accent-pink);"></i> ' + t('p.quizTitle') + '</div>';

                const qWrap = document.createElement('div');
                qWrap.className = 'practice-questions';
                qCard.appendChild(qWrap);

                const result = document.createElement('div');
                qCard.appendChild(result);

                renderQuestions(qWrap, chapter.questions, (correct) => {
                    const total = chapter.questions.length;
                    award(15 + correct * 5, 5 + correct * 2);
                    result.className = 'practice-result';
                    result.textContent = t('p.result', { c: correct, t: total }) + '  +' + (15 + correct * 5) + ' XP  +' + (5 + correct * 2) + ' Gold';
                });

                contentContainer.appendChild(qCard);
            }

            // Chapter navigation bar (Previous / Next)
            const navBar = document.createElement('div');
            navBar.className = 'chapter-nav-bar';

            if (chapterIndex > 0) {
                const prevBtn = document.createElement('button');
                prevBtn.type = 'button';
                prevBtn.className = 'reader-ctrl-btn';
                prevBtn.innerHTML = '<i class="fa-solid fa-chevron-left"></i> Previous Chapter';
                prevBtn.onclick = () => openBookReader(book, chapterIndex - 1);
                navBar.appendChild(prevBtn);
            } else {
                navBar.appendChild(document.createElement('div'));
            }

            const backBtnMid = document.createElement('button');
            backBtnMid.type = 'button';
            backBtnMid.className = 'reader-ctrl-btn';
            backBtnMid.innerHTML = '<i class="fa-solid fa-book-open"></i> ' + t('p.backBooks');
            backBtnMid.onclick = () => renderReading(book.level, 'books');
            navBar.appendChild(backBtnMid);

            if (chapterIndex < book.chapters.length - 1) {
                const nextBtn = document.createElement('button');
                nextBtn.type = 'button';
                nextBtn.className = 'reader-ctrl-btn active';
                nextBtn.innerHTML = 'Next Chapter <i class="fa-solid fa-chevron-right"></i>';
                nextBtn.onclick = () => openBookReader(book, chapterIndex + 1);
                navBar.appendChild(nextBtn);
            } else {
                navBar.appendChild(document.createElement('div'));
            }

            contentContainer.appendChild(navBar);
        }

        renderChapterBody();
        root.appendChild(card);
    }

    function openReading(item, lv, backToList) {
        const root = document.getElementById('reading');
        root.innerHTML = '';
        const card = document.createElement('div');
        card.className = 'glass-card';
        card.appendChild(backButton(t('p.backReading'), () => renderReading(lv, 'passages')));
        const title = document.createElement('div');
        title.className = 'card-title';
        title.textContent = item.title;
        card.appendChild(title);

        const passage = document.createElement('div');
        passage.className = 'reading-passage';
        passage.textContent = item.passage;
        card.appendChild(passage);
        const code = (typeof LANG_PACK_CODES !== 'undefined' && typeof player !== 'undefined') ? LANG_PACK_CODES[player.nativeLanguage] : null;
        const nativePassage = (code && item['passage_' + code]) || item.passage_en;
        const toggleLabel = (code && code !== 'en') ? (t('p.showTranslation') || 'Show translation') : t('p.showEn');
        if (nativePassage) card.appendChild(detailsBlock(toggleLabel, nativePassage));

        const qWrap = document.createElement('div');
        qWrap.className = 'practice-questions';
        card.appendChild(qWrap);
        const result = document.createElement('div');
        card.appendChild(result);
        renderQuestions(qWrap, item.questions, (correct) => {
            const total = item.questions.length;
            award(10 + correct * 3, correct * 2);
            result.className = 'practice-result';
            result.textContent = t('p.result', { c: correct, t: total }) + '  +' + (10 + correct * 3) + ' XP';
        });
        root.appendChild(card);
    }

    // ---- LISTENING ----
    function renderListening(defaultLevel) {
        const root = document.getElementById('listening');
        if (!root) return;
        loadScript('js/data/listening.js', () => {
            const bank = window.LISTENING_BANK || {};
            const validLevels = ['N5', 'N4', 'N3', 'N2', 'N1'];
            let level = (defaultLevel && validLevels.includes(defaultLevel.toUpperCase())) ? defaultLevel.toUpperCase() : 'N5';
            root.innerHTML = '';
            const head = document.createElement('div');
            head.className = 'glass-card';
            head.innerHTML = '<div class="card-title"><i class="fa-solid fa-headphones" style="color: var(--accent-pink);"></i> ' + t('p.listeningTitle') + '</div>'
                + '<p class="practice-intro">' + t('p.listeningIntro') + '</p>';
            const body = document.createElement('div');
            head.appendChild(body);
            root.appendChild(head);

            const showList = (lv) => {
                level = lv;
                body.innerHTML = '';
                body.appendChild(levelPills(level, showList));
                const items = bank[lv] || [];
                if (!items.length) {
                    const p = document.createElement('p');
                    p.className = 'practice-empty';
                    p.textContent = t('p.comingListening', { lv });
                    body.appendChild(p);
                    return;
                }
                items.forEach(it => {
                    const c = document.createElement('button');
                    c.type = 'button';
                    c.className = 'practice-item';
                    const t = document.createElement('span');
                    t.className = 'practice-item-title';
                    t.textContent = it.title;
                    c.appendChild(t);
                    c.onclick = () => openListening(it);
                    body.appendChild(c);
                });
            };
            showList(level);
        });
    }

    function openListening(item) {
        const root = document.getElementById('listening');
        root.innerHTML = '';
        const card = document.createElement('div');
        card.className = 'glass-card';
        card.appendChild(backButton(t('p.backListening'), () => renderListening()));
        const title = document.createElement('div');
        title.className = 'card-title';
        title.textContent = item.title;
        card.appendChild(title);

        // Play controls: play + speed. Script is hidden until answered.
        const controls = document.createElement('div');
        controls.className = 'listening-controls';
        let rate = 0.9;
        const play = document.createElement('button');
        play.type = 'button';
        play.className = 'btn listening-play';
        play.innerHTML = '<i class="fa-solid fa-play"></i> ' + t('p.playAudio');
        play.onclick = () => { if (typeof speakJapanese === 'function') speakJapanese(item.script, rate); };
        controls.appendChild(play);
        [[t('p.slow'), 0.6], [t('p.normal'), 0.9], [t('p.fast'), 1.1]].forEach(([lab, r], i) => {
            const b = document.createElement('button');
            b.type = 'button';
            b.className = 'listening-speed' + (r === rate ? ' active' : '');
            b.textContent = lab;
            b.onclick = () => {
                rate = r;
                controls.querySelectorAll('.listening-speed').forEach(x => x.classList.remove('active'));
                b.classList.add('active');
            };
            controls.appendChild(b);
        });
        card.appendChild(controls);

        const qWrap = document.createElement('div');
        qWrap.className = 'practice-questions';
        card.appendChild(qWrap);
        const after = document.createElement('div');
        card.appendChild(after);
        renderQuestions(qWrap, item.questions, (correct) => {
            const total = item.questions.length;
            award(10 + correct * 3, correct * 2);
            after.innerHTML = '';
            const res = document.createElement('div');
            res.className = 'practice-result';
            res.textContent = t('p.result', { c: correct, t: total }) + '  +' + (10 + correct * 3) + ' XP';
            after.appendChild(res);
            const script = document.createElement('div');
            script.className = 'listening-script';
            script.textContent = item.script;
            after.appendChild(script);
            const code = (typeof LANG_PACK_CODES !== 'undefined' && typeof player !== 'undefined') ? LANG_PACK_CODES[player.nativeLanguage] : null;
            const nativeTranscript = (code && item['transcript_' + code]) || item.transcript_en;
            const toggleLabel = (code && code !== 'en') ? (t('p.showTranslation') || 'Show translation') : t('p.showEn');
            if (nativeTranscript) after.appendChild(detailsBlock(toggleLabel, nativeTranscript));
        });
        root.appendChild(card);
    }

    // ---- MOCK EXAM ----
    // Three timed sections with sectional pass thresholds, mirroring the real
    // JLPT gating (overall >= 100/180 AND each section >= 19/60).
    function renderExam(defaultLevel) {
        const root = document.getElementById('exam');
        if (!root) return;
        // exam pulls from both banks
        loadScript('js/data/reading.js', () => loadScript('js/data/listening.js', () => {
            const validLevels = ['N5', 'N4', 'N3', 'N2', 'N1'];
            let level = (defaultLevel && validLevels.includes(defaultLevel.toUpperCase())) ? defaultLevel.toUpperCase() : 'N5';
            root.innerHTML = '';
            const head = document.createElement('div');
            head.className = 'glass-card';
            head.innerHTML = '<div class="card-title"><i class="fa-solid fa-file-pen" style="color: var(--accent-purple);"></i> ' + t('p.examTitle') + '</div>'
                + '<p class="practice-intro">' + t('p.examIntro') + '</p>';
            const body = document.createElement('div');
            head.appendChild(body);
            root.appendChild(head);

            const rebuild = (lv) => {
                level = lv;
                body.innerHTML = '';
                body.appendChild(levelPills(level, rebuild));
                const start = document.createElement('button');
                start.type = 'button';
                start.className = 'btn exam-start';
                start.innerHTML = '<i class="fa-solid fa-stopwatch"></i> ' + t('p.startExam', { lv });
                start.onclick = () => runExam(lv);
                body.appendChild(start);
            };
            rebuild(level);
        }));
    }

    function buildVocabSection(lv, count) {
        // reuse the arena's procedural vocab/reading questions; normalise answer to index
        if (typeof generateProceduralQuestions !== 'function') return [];
        const raw = generateProceduralQuestions(lv, count) || [];
        return raw.filter(q => q && q.options && q.options.length).map(q => ({
            q: q.q,
            options: q.options,
            answer: Math.max(0, q.options.indexOf(q.answer))
        }));
    }

    function runExam(lv) {
        const readingBank = (window.READING_BANK || {})[lv] || [];
        const listeningBank = (window.LISTENING_BANK || {})[lv] || [];
        const sections = [
            { key: 'Language Knowledge', type: 'vocab', questions: buildVocabSection(lv, 10) },
            { key: 'Reading', type: 'reading', items: pickN(readingBank, 2) },
            { key: 'Listening', type: 'listening', items: pickN(listeningBank, 2) }
        ];

        const root = document.getElementById('exam');
        root.innerHTML = '';
        const card = document.createElement('div');
        card.className = 'glass-card';
        root.appendChild(card);

        // Timer bar
        const bar = document.createElement('div');
        bar.className = 'exam-bar';
        const timeEl = document.createElement('span');
        timeEl.className = 'exam-timer';
        bar.appendChild(timeEl);
        const submitBtn = document.createElement('button');
        submitBtn.type = 'button';
        submitBtn.className = 'btn exam-submit';
        submitBtn.textContent = t('p.submit');
        bar.appendChild(submitBtn);
        card.appendChild(bar);

        const secLabel = (k) => t(k === 'Language Knowledge' ? 'p.secLK' : k === 'Reading' ? 'p.secReading' : 'p.secListening');
        // track score per section: {section: {correct, total}}
        const score = {};
        sections.forEach(s => { score[s.key] = { correct: 0, total: 0 }; });

        // record answers: for each rendered question, store correctness getter
        const graders = [];

        sections.forEach(sec => {
            const secEl = document.createElement('div');
            secEl.className = 'exam-section';
            const h = document.createElement('div');
            h.className = 'exam-section-title';
            h.textContent = secLabel(sec.key);
            secEl.appendChild(h);

            if (sec.type === 'vocab') {
                sec.questions.forEach(q => graders.push(mkGrader(secEl, sec.key, q)));
            } else {
                (sec.items || []).forEach(item => {
                    if (sec.type === 'reading') {
                        const p = document.createElement('div');
                        p.className = 'reading-passage';
                        p.textContent = item.passage;
                        secEl.appendChild(p);
                    } else {
                        const play = document.createElement('button');
                        play.type = 'button';
                        play.className = 'btn listening-play';
                        play.innerHTML = '<i class="fa-solid fa-play"></i> ' + t('p.playAudio');
                        play.onclick = () => { if (typeof speakJapanese === 'function') speakJapanese(item.script, 0.9); };
                        secEl.appendChild(play);
                    }
                    (item.questions || []).forEach(q => graders.push(mkGrader(secEl, sec.key, q)));
                });
            }
            card.appendChild(secEl);
        });

        // Grader: renders a question, returns {section, isCorrect()}.
        function mkGrader(parent, sectionKey, q) {
            score[sectionKey].total++;
            const box = document.createElement('div');
            box.className = 'practice-q';
            const qt = document.createElement('div');
            qt.className = 'practice-q-text';
            qt.textContent = q.q;
            box.appendChild(qt);
            const opts = document.createElement('div');
            opts.className = 'practice-opts';
            let chosen = -1;
            q.options.forEach((opt, oi) => {
                const ob = document.createElement('button');
                ob.type = 'button';
                ob.className = 'practice-opt';
                ob.textContent = opt;
                ob.onclick = () => {
                    chosen = oi;
                    opts.querySelectorAll('.practice-opt').forEach(x => x.classList.remove('chosen'));
                    ob.classList.add('chosen');
                };
                opts.appendChild(ob);
            });
            box.appendChild(opts);
            parent.appendChild(box);
            return { sectionKey, opts, q, isCorrect: () => chosen === q.answer, reveal: () => {
                opts.children[q.answer] && opts.children[q.answer].classList.add('right');
            } };
        }

        // Timer: ~1 min per question, min 5 min.
        let remaining = Math.max(300, graders.length * 45);
        const fmt = (s) => String(Math.floor(s / 60)).padStart(2, '0') + ':' + String(s % 60).padStart(2, '0');
        timeEl.textContent = '⏱ ' + fmt(remaining);
        let done = false;
        const tick = setInterval(() => {
            remaining--;
            timeEl.textContent = '⏱ ' + fmt(remaining);
            if (remaining <= 0) finish();
        }, 1000);

        function finish() {
            if (done) return;
            done = true;
            clearInterval(tick);
            graders.forEach(g => {
                if (g.isCorrect()) score[g.sectionKey].correct++;
                g.reveal();
            });
            // scale each section to /60
            let overall = 0; const lines = []; let sectionalFail = false;
            sections.forEach(s => {
                const sc = score[s.key];
                const scaled = sc.total ? Math.round((sc.correct / sc.total) * 60) : 0;
                overall += scaled;
                if (scaled < 19) sectionalFail = true;
                lines.push(`${secLabel(s.key)}: ${scaled}/60${scaled < 19 ? '  ✕ ' + t('p.below19') : ''}`);
            });
            const passed = overall >= 100 && !sectionalFail;
            award(passed ? 80 : Math.round(overall / 3), passed ? 40 : 10);

            const res = document.createElement('div');
            res.className = 'exam-result ' + (passed ? 'pass' : 'fail');
            res.innerHTML = `<div class="exam-verdict">${passed ? t('p.pass') : t('p.notYet')} — ${overall}/180</div>`
                + lines.map(l => `<div class="exam-line">${l}</div>`).join('')
                + `<div class="exam-note">${t('p.passNote')}</div>`;

            // Social Brag / Viral Share Tray
            const shareText = `🏯 I scored ${overall}/180 (${passed ? 'PASS 🎉' : 'NOT YET 💪'}) on the JLPT ${lv} Mock Exam on KotoQuest!\n`
                + lines.map(l => `• ${l}`).join('\n') + '\n\n'
                + `Free, offline JLPT study academy: https://kotoquest.pages.dev/#exam?level=${lv}`;

            const shareTray = document.createElement('div');
            shareTray.className = 'share-tray';
            shareTray.innerHTML = `
                <span class="share-label"><i class="fa-solid fa-share-nodes"></i> Share:</span>
                ${passed ? '<button type="button" class="share-btn share-btn-primary" id="btn-claim-cert"><i class="fa-solid fa-award"></i> Claim Certificate</button>' : ''}
                <button type="button" class="share-btn share-btn-primary" id="btn-share-native"><i class="fa-solid fa-share-from-square"></i> Share Score</button>
                <a class="share-btn share-btn-wa" href="https://api.whatsapp.com/send?text=${encodeURIComponent(shareText)}" target="_blank" rel="noopener"><i class="fa-brands fa-whatsapp"></i> WhatsApp</a>
                <a class="share-btn share-btn-x" href="https://twitter.com/intent/tweet?text=${encodeURIComponent(shareText)}" target="_blank" rel="noopener"><i class="fa-brands fa-x-twitter"></i> Post</a>
                <button type="button" class="share-btn share-btn-copy" id="btn-share-copy"><i class="fa-solid fa-copy"></i> Copy</button>
            `;
            res.appendChild(shareTray);

            const btnCert = shareTray.querySelector('#btn-claim-cert');
            if (btnCert) {
                btnCert.onclick = () => {
                    if (typeof window.openCertificateModal === 'function') {
                        window.openCertificateModal();
                    } else {
                        window.location.hash = '#certificate';
                    }
                };
            }

            const btnNative = shareTray.querySelector('#btn-share-native');
            if (btnNative) {
                btnNative.onclick = () => {
                    if (navigator.share) {
                        navigator.share({
                            title: `KotoQuest - JLPT ${lv} Mock Exam`,
                            text: shareText,
                            url: `https://kotoquest.pages.dev/#exam?level=${lv}`
                        }).catch(() => {});
                    } else {
                        navigator.clipboard.writeText(shareText);
                        if (typeof window.showToast === 'function') window.showToast('Score copied to clipboard!');
                    }
                };
            }
            const btnCopy = shareTray.querySelector('#btn-share-copy');
            if (btnCopy) {
                btnCopy.onclick = () => {
                    navigator.clipboard.writeText(shareText);
                    if (typeof window.showToast === 'function') window.showToast('Score copied to clipboard!');
                };
            }

            card.insertBefore(res, card.children[1]);
            const retry = document.createElement('button');
            retry.type = 'button';
            retry.className = 'btn';
            retry.style.marginTop = '14px';
            retry.textContent = t('p.backExam');
            retry.onclick = () => renderExam(lv);
            card.appendChild(retry);
            res.scrollIntoView({ block: 'start', behavior: 'smooth' });
        }
        submitBtn.onclick = finish;
    }

    // Lazy-render each module the first time its tab is opened (and on resume).
    const RENDERERS = { reading: renderReading, listening: renderListening, exam: renderExam };
    const rendered = {};
    function ensureRendered(tab, level) {
        if (!RENDERERS[tab]) return;
        rendered[tab] = true;
        RENDERERS[tab](level);
    }
    // Allow external callers to render a practice tab directly with an optional level
    window.renderPracticeTab = function(tab, level) {
        if (RENDERERS[tab]) {
            ensureRendered(tab, level);
        }
    };
    // Allow external callers (e.g. applyNativeLanguageNuances in app.js) to re-render
    // practice modules in the newly selected language.
    window.refreshPracticeModules = function() {
        for (const tab in rendered) {
            if (rendered[tab] && RENDERERS[tab]) {
                RENDERERS[tab]();
            }
        }
    };

    document.addEventListener('DOMContentLoaded', () => {
        const nav = document.getElementById('main-nav');
        if (nav) nav.addEventListener('click', (e) => {
            const t = e.target.closest('.nav-tab');
            if (t) ensureRendered(t.getAttribute('data-tab'));
        });
        // resume: if the app restored one of our tabs, render it
        if (typeof player !== 'undefined' && player.lastTab && RENDERERS[player.lastTab]) {
            ensureRendered(player.lastTab);
        }
    });
})();
